{
 "title": "Internet Speed Monitor",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"packet_loss\")\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"ping_latency\")\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"ping_jitter\")\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"download_bandwidth\")\r\n  |> map(fn: (r) => ({ _value: r._value / uint(v: 125000), _time: r._time }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Download Speed by Server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"download_bandwidth\")\r\n  |> group(columns: [\"server_id\", \"server_location\"])\r\n  |> map(fn: (r) => ({ _value: r._value / uint(v: 125000), _time: r._time, server_id: r.server_id, server_location: r.server_location }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"upload_bandwidth\")\r\n  |> map(fn: (r) => ({ _value: r._value / uint(v: 125000), _time: r._time }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Upload Speed by Server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"upload_bandwidth\")\r\n  |> group(columns: [\"server_id\", \"server_location\"])\r\n  |> map(fn: (r) => ({ _value: r._value / uint(v: 125000), _time: r._time, server_id: r.server_id, server_location: r.server_location }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}